language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      
script:
- mvn -f modules/pom.xml clean package integration-test

jdk:
  - oraclejdk8


cache:
  directories:
  - $HOME/.m2
